name: snaps-${ENV}

services:
  db-test:
    container_name: snaps-db-test
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "${POSTGRES_PORT}:5432"
